export const categories = [
  { id: 'trending', title: 'Trending Now' },
  { id: 'topRated', title: 'Top Rated' },
  { id: 'action', title: 'Action Thrillers' },
  { id: 'comedy', title: 'Comedies' },
  { id: 'horror', title: 'Horror Movies' },
  { id: 'romance', title: 'Romance Movies' },
  { id: 'documentary', title: 'Documentaries' },
];

export const movies = [
  {
    id: 1,
    title: 'Stranger Things',
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    poster_path: 'https://placehold.co/500x750/000000/e50914?text=Stranger+Things',
    backdrop_path: 'https://placehold.co/1920x1080/000000/e50914?text=Stranger+Things',
    match: '98% Match',
    rating: 'TV-14',
    duration: '4 Seasons',
    genre_ids: ['trending', 'action', 'horror', 'scifi'],
  },
  {
    id: 2,
    title: 'The Witcher',
    overview: 'Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.',
    poster_path: 'https://placehold.co/500x750/000000/e50914?text=The+Witcher',
    backdrop_path: 'https://placehold.co/1920x1080/000000/e50914?text=The+Witcher',
    match: '95% Match',
    rating: 'TV-MA',
    duration: '2 Seasons',
    genre_ids: ['trending', 'action', 'fantasy'],
  },
  {
    id: 3,
    title: 'Inception',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    poster_path: 'https://placehold.co/500x750/000000/e50914?text=Inception',
    backdrop_path: 'https://placehold.co/1920x1080/000000/e50914?text=Inception',
    match: '97% Match',
    rating: 'PG-13',
    duration: '2h 28m',
    genre_ids: ['topRated', 'action', 'scifi'],
  },
  {
    id: 4,
    title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    poster_path: 'https://placehold.co/500x750/000000/e50914?text=The+Dark+Knight',
    backdrop_path: 'https://placehold.co/1920x1080/000000/e50914?text=The+Dark+Knight',
    match: '99% Match',
    rating: 'PG-13',
    duration: '2h 32m',
    genre_ids: ['topRated', 'action'],
  },
  {
    id: 5,
    title: 'Avengers: Endgame',
    overview: 'After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos\' actions and restore balance to the universe.',
    poster_path: 'https://placehold.co/500x750/000000/e50914?text=Avengers:+Endgame',
    backdrop_path: 'https://placehold.co/1920x1080/000000/e50914?text=Avengers:+Endgame',
    match: '96% Match',
    rating: 'PG-13',
    duration: '3h 1m',
    genre_ids: ['trending', 'action', 'scifi'],
  },
  {
    id: 6,
    title: 'Spider-Man: Into the Spider-Verse',
    overview: 'Miles Morales is juggling his life between being a high school student and being a spider-man. When Wilson "Kingpin" Fisk uses a super collider, others from across the Spider-Verse are transported to this dimension.',
    poster_path: 'https://placehold.co/500x750/000000/e50914?text=Into+The+Spider-Verse',
    backdrop_path: 'https://placehold.co/1920x1080/000000/e50914?text=Into+The+Spider-Verse',
    match: '98% Match',
    rating: 'PG',
    duration: '1h 57m',
    genre_ids: ['trending', 'action', 'animation'],
  },
];
